const pipelineAustin  = ['Aceable', 'ePatientFinder', 'eRelevance Corp.', 'InforcePRO', 'Isocline', 'Liveoak Technologies', 'Message.io', 'PenPal Schools', 'Digital Pharmacist Inc.', 'Virtuix', 'AlertMedia', 'Bold Metrics', 'Clearhead', 'Clarify Inc', 'Self Lender', 'data.world', 'Embark', 'Everfest', 'eyeQ', 'EverlyWell', 'Hangar', 'Help.com', 'Hive9', 'Homads', 'Keystoke', 'ListingSpark', 'Medici', 'Meretz', 'Nexd', 'Ojo Labs', 'OnceThere', 'Querium', 'Opcity', 'RigUP', 'ScaleFactor', 'SchoolLinks', 'SocialCare by Health Symmetric', 'SparkCognition', 'Student Loan Genius', 'Tenfold', 'Twyla', 'UnaliWear', 'WholeSplit', 'Zengistics' ];

const pipelineNYC = ['innRoad','SecurityScorecard','TripleLift','Eyeview','eLearning Mind','The Hackerati','CompStak','RapidSOS','Reelio','PolicyGenius','CB Insights','xAd','Managed by Q','Appboy','Thuzio','Joor','BrandYourself','Greenhouse Software','Justworks','BeenVerified','itBit','Canary','Conductor',"Maker's Row",'Betterment','SeatGeek','Grovo','DigitalOcean','Artsy','GameChanger','RebelMouse','Noom','Casper','Greatist'];

const pipelineLA = ['hyperloop-one', 'mobile-majority', 'omaze', 'patientpop', 'realtymogulcom', 'servicetitan-inc', 'signal-sciences', 'goguardian', 'hopskipdrive', 'attn', 'heal', 'homehero', 'skurt', 'makerskit', 'creators-media-inc', 'divy', 'airmap', 'appetize', 'azubu', 'brilliant-bicycle-co', 'bringhub', 'clutter', 'enervee', 'famebit', 'fieldtest', 'five-four-club', 'float', 'freedompop', 'hawke-media', 'hustle', 'inspire', 'iristv', 'little-labs', 'lucky-day', 'mobcrush', 'open-listing', 'panjo', 'parachute', 'purple-services-inc', 'saucey', 'sense360', 'service-technologies', 'spidr-tech', 'twenty20', 'two-bit-circus', 'videoamp', 'voter', 'wagespot', 'waivecar', 'wevr'];
const lessons = [
{Title: 'lesson 1', Summary: 'How to be good at anything - The man in the mirror!', Content: 'Knowing Yourself  -  A key component to success is to know build on what you can do well and continuously work on what you cannot do well. Since you are beginning I would suggest taking the time to write down a list of things you have been recognized for by managers, colleagues, friends, relatives and customers in the past. After the list of strengths make a list of weaknesses you have, this might be more difficult, but everyone has them. The best way to see progress is to continuously to ask for feedback. Also, be sincerely be open to feedback and follow through with suggestions. Best feedback to get is one-on-one if possible. Obviously this is not a short term goal so keep at it!'},
{Title: 'lesson 2', Summary: 'Simple Truths', Content: 'People do business with people the like - Respect is everything, show respect to every candidate you talk to, this the first step to getting them to like you. - There are a lot of recruiters calling these people, differentiate yourself by being interested in them, their skills, their past & future…not trying to impress them.  - People love to talk about themselves, so being sincerely interested in them will naturally make it easier for them to like you and work with you.'},
{Title: 'lesson 3', Summary: 'Critical Tasks', Content: 'Excelling at Critical Tasks - There are very many tasks in the day to day of recruiting. Here are just a few:  • Listen – interviewing, qualifying, etc. • Develop and manage relationships  • Managing your bandwidth and activity – Recruitment studio, organization, etc.  • Getting candidate commitment (more on this later). Like anything  effort, discipline and getting feedback will be key.'},
{Title: 'lesson 4', Summary: 'Asking the right questions', Content: 'Asking the right questions - Every conversation is like a navigating a trip... there are a million ways to get from A to B, your job is to focus on making the right turns to get there and get the most information possible. - Each person you talk to will lie at least once while on the phone with you...ask questions to dig deeper and validate the information. You made how much? So how much did you make before that? Before that? Before that? - Reflect their tone, style of talk and repeat their words back to them and use that to segue to the next questions. - What do YOU need to know to make a decision on whether or not this candidate is qualified? Ask those questions.'},
{Title: 'lesson 5', Summary: 'Attitude - Getting out of your own way', Content: 'Attitude -  Staffing is one of the most difficult sale professions out there, because we are selling/presenting candidates’ expertise to managers, the benefits of a particular position to candidates, and continuously qualifying them. - This is essentially more complex because people are fickle and are on both sides of the equation….meaning we are aiming for moving targets (candidates) and basing our search off of moving targets (job orders that change and manager’s preferences) - With this in mind it is important to note that the better you stick to the fundamentals, the better your conversations get'},
{Title: 'lesson 6', Summary: 'AIDA & LOCKDOWN', Content: 'A – ATTENTION I – INTEREST D – DECISION A – ACTION A – Goal: Focusing on the target audience. Seeking people who will respond to what you are sharing. Generating interest. Questions: Do you have their attention? Is this a relevant opportunity? Similar to what they’ve done? How can you get their attention – On the phone? Email? In person? Do you have this info? I – Goal: It is all about them and getting them employed. Get them to answer the right questions. Questions: Is this good for them? Do they want it? Is this opportunity relevant to them? Same skill set? Do they have the education for it? Is this within their pay range? Commuting range? What are their goals? D – Goal: Spell out how this is good for them and get them to go with you. Have they committed to you? To the opportunity? To follow through? A – Goal: Setting expectation, follow through and commitment steps. LOCKDOWN: what commitment steps have you put forward? What will they do? How? What loop will you initiate/close? What is the time line expectation?'},
{Title: 'lesson 7', Summary: 'Basic Recruiting Script', Content: 'Write this section out'},
{Title: 'lesson 8', Summary: '360 Management', Content: 'Write this section out'}
];

const questions = [
{questionText: 'Question1, lesson 1', lessonId: 1},
{questionText: 'Question2, lesson 2', lessonId: 2},
{questionText: 'Question3, lesson 3', lessonId: 3},
{questionText: 'Question4, lesson 4', lessonId: 4},
{questionText: 'Question5, lesson 5', lessonId: 5},
{questionText: 'Question6, lesson 6', lessonId: 6},
{questionText: 'Question7, lesson 7', lessonId: 7},
{questionText: 'Question8, lesson 8', lessonId: 8}
];
module.exports = {pipelineLA: pipelineLA, lessons: lessons, questions: questions, pipelineNYC: pipelineNYC, pipelineAustin: pipelineAustin};
