const lessons = [
{Title: 'Lesson 1', Summary: 'Being nervous on the phone', Content: 'If you are nervous a the prospect of calling leaders at companies in your city then I have great news for you! #1 - You are paying attention. #2 - You are worried about making bad impression. First off, you would be better served by focuing on how to do a good job rather than how to not mess up (those are not the same thing). The simple is two fold: A.) You have to get our of your own way by remembering that: this is not about you. Making a phone call or sending an email is not about you, how you feel or who you are in any way, shape or form. Thinking this would be an indication of missing the big picture. It is about our community, which is much bigger than ourselves and has a positive effect on peoples lives. If you really do not like the idea of making phone calls to people for the sake of helping build our community then I would ask you to get over it and carry on. #2 People want to naturally want to help, the biggest challenge is not asking people to help, it is just getting in contact with them for a short introduction'},
{Title: 'Lesson 2', Summary: 'Meeting of the Minds', Content: 'Communication is one of the most fundamental engineering skills out there. We are reaching out to people who have expertise as engineers, managers, leads, etc and as professionals they will have littl tolerance for people that communicate poorly while their guard is up (first conversation). This is why we will be working with a script.  Good communication leads to mutual understanding. When people feel understood and understand you communication comes fun and exciting, opportunity for collaboration '},
{Title: 'lesson 3', Summary: 'Asking the right questions', Content: 'Asking the right questions - Every conversation is like a decision tree... there are a many ways to get from the root to a leaf, your job is to focus on making the right turns. The best way to do this would be by intently listening and engaging, not by politely waiting for your turn to talk.'},
{Title: 'lesson 4', Summary: 'Handling Objections - Easily one of the most useful skills in life', Content: 'Some will want to help, but their knee-jerk reaction will be to wish you well and say no. That is totally fine! We are not going to push people into giving our stuents a talk, that would obviously defeat the purpose of what we are working toward. We will work on these within the script'
{Title: 'lesson 5', Summary: 'Establishing expectations', Content: 'Write this section out'},
{Title: 'lesson 6', Summary: 'Staying in Touch', Content: 'Write this section out'}
];

module.exports = { lessons: lessons}
